name: weight_tracker_ar
description: متابعة الوزن - Flutter Android APK direct.
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
